name: ESLint

on:
  push:
  pull_request:
    types: [opened, edited, ready_for_review]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-eslint@v1
        with:
          node-version: "20"
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: "src/"
